controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# index:
#     path: /first
#     controller: App\Controller\FirstController::homepage
